# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Build

env:
  dotnet_version: 7.0.x
  project_path: ./src/SkyWriter.Console/
  publish_path: bin/Release/net7.0/win-x64/publish/

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.dotnet_version }}
    - name: Restore dependencies
      run: dotnet restore ${{ env.project_path }}
    - name: Build
      run: dotnet build ${{ env.project_path }} --no-restore
    - name: Publish
      run: dotnet publish ${{ env.project_path }} -c Release
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: SkyWriter win-x64 Release
        path: '${{ env.project_path }}${{ env.publish_path }}'

  release:
    name: Draft Release
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: SkyWriter win-x64 Release
        path: ./bundles/
    - name: Draft Rekease
      uses: actions/create-release@1
      with:
        tag_name: v${{ needs.checktag.outputs.version }}
        release_name: SkyWriter v${{ needs.checktag.outputs.version }}
        body: "## SkyWriter v${{ needs.checktag.outputs.version }} Release Notes\n\n"
        draft: true
        prerelease: false
